// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/runner/runner.proto

package runner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Stdin         string                 `protobuf:"bytes,3,opt,name=stdin,proto3" json:"stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	mi := &file_proto_runner_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_runner_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *RunCodeRequest) GetStdin() string {
	if x != nil {
		return x.Stdin
	}
	return ""
}

type RunCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	mi := &file_proto_runner_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_runner_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_runner_runner_proto_rawDescGZIP(), []int{1}
}

func (x *RunCodeResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunCodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_runner_runner_proto protoreflect.FileDescriptor

const file_proto_runner_runner_proto_rawDesc = "" +
	"\n" +
	"\x19proto/runner/runner.proto\x12\x06runner\"V\n" +
	"\x0eRunCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05stdin\x18\x03 \x01(\tR\x05stdin\"?\n" +
	"\x0fRunCodeResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2K\n" +
	"\rRunnerService\x12:\n" +
	"\aRunCode\x12\x16.runner.RunCodeRequest\x1a\x17.runner.RunCodeResponseB-Z+github.com/VJ-2303/code-runner/proto/runnerb\x06proto3"

var (
	file_proto_runner_runner_proto_rawDescOnce sync.Once
	file_proto_runner_runner_proto_rawDescData []byte
)

func file_proto_runner_runner_proto_rawDescGZIP() []byte {
	file_proto_runner_runner_proto_rawDescOnce.Do(func() {
		file_proto_runner_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_runner_runner_proto_rawDesc), len(file_proto_runner_runner_proto_rawDesc)))
	})
	return file_proto_runner_runner_proto_rawDescData
}

var file_proto_runner_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_runner_runner_proto_goTypes = []any{
	(*RunCodeRequest)(nil),  // 0: runner.RunCodeRequest
	(*RunCodeResponse)(nil), // 1: runner.RunCodeResponse
}
var file_proto_runner_runner_proto_depIdxs = []int32{
	0, // 0: runner.RunnerService.RunCode:input_type -> runner.RunCodeRequest
	1, // 1: runner.RunnerService.RunCode:output_type -> runner.RunCodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_runner_runner_proto_init() }
func file_proto_runner_runner_proto_init() {
	if File_proto_runner_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_runner_runner_proto_rawDesc), len(file_proto_runner_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_runner_runner_proto_goTypes,
		DependencyIndexes: file_proto_runner_runner_proto_depIdxs,
		MessageInfos:      file_proto_runner_runner_proto_msgTypes,
	}.Build()
	File_proto_runner_runner_proto = out.File
	file_proto_runner_runner_proto_goTypes = nil
	file_proto_runner_runner_proto_depIdxs = nil
}
